### ISSUE TITLE
Things to do:

### ISSUE THREAD

**Issue by MercuryHunter** [MercuryHunter/GnomesInTheDark#1]
## Done:
- [x] Levels: Dylan
- [x] Player movement: Jonathan
- [x] Player Models: Sebast
- [x] Enemy Models: Sebast
- [x] Inventory System: Dylan
- [x] Lantern: Jonathan/Sebast: Found: Modular Medieval Lanterns, check it out
- [x] Item Interaction: Dylan (like inventory)
- [x] 3D Environment and Cog Machine: Dylan
## Jonathan:
- [x] Split-screen co-op: Cameras + UI (Support for 2-4 players)
- [x] Split-screen co-op: Controls
- [x] Sprint (whoops)
- [x] Split-screen co-op: Object positions: Decision - model attached (not camera attached)
- [ ] Split-screen co-op: Audio? Can only have one audio listener, but need to have multiple
- [x] Refactor Code
- [x] Lantern collision sphere to go with lantern flicker
- [x] Move Lantern Script
- [x] Normals on wall texture script
## Whoever
- [x] AI
## Sebast
- [x] Item Models: Cogs, Picks, Machine, Etc.
- [x] Design a basic UI (goes with split screen)
## Dylan
- [x] So many objects and traps and cogs

**Comment by MercuryHunter** [comment]
If you could please comment as necessary on discussion points, and add new todos here, they can be added to the list :)

**Comment by hrbseb001** [comment]
In terms of minimum player count I think 1 is 'acceptable', but the game will be very difficult. You can play it as one player but if a monster catches you, there will be nobody to save you and you will be unable to do some puzzles. The game strongly recommends 2 or more people but doesn't stop you from playing single player? This depends on whether completing the co-op obstacles we create, is essential to completing the game. We could make co-op obstacles essential or make them just give really nice bonus stuff that make the game less difficult. In terms of max players we support. This is something we will be able to better gauge when we start implementing split screen. 4 players is the planned max, but it may turn out when we start doing this later that only 2 players would be better suited, performance and screen space wise.
